import { NextRequest, NextResponse } from "next/server";
import { APIConnectionTimeoutError } from "openai";
import { scoreInstruction } from "@/lib/evaluate-core";
import { getTenantModelOverrides, getCurrentUserContext } from "@/lib/server-auth";
import { getSupabaseServer } from "@/lib/supabase";
import { mergeTeamCategories, flattenCategories } from "@/lib/mock-data";
import type { InstructionDraft, AssigneeRank, SupportMode, TeamCategoryOverride } from "@/lib/mock-data";

const VALID_RANKS: AssigneeRank[] = ["A", "B", "C", "D"];

// Production logs showed repeated "Task timed out after 120 seconds" 504s here —
// confirmed as the actual Vercel cutoff (not silently downgraded from a lower plan
// limit). This happened even on the standard-importance path (gpt-4.1-mini, non-
// reasoning), not just the gpt-5.5 reasoning path used for high-importance items —
// likely transient OpenAI-side latency/rate-limiting under bursty request patterns
// rather than reasoning-model latency specifically. Raised to 180s (Vercel Pro
// allows up to 300s) to absorb slow responses regardless of cause.
export const maxDuration = 180;

export async function POST(req: NextRequest) {
  if (!process.env.OPENAI_API_KEY) {
    return NextResponse.json({ error: "OPENAI_API_KEY is not configured" }, { status: 500 });
  }

  let body: { draft: InstructionDraft; assignee_rank?: string; support_mode?: string; team_id?: string | null };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const { draft, assignee_rank, support_mode, team_id } = body ?? {};
  if (!draft?.overview?.trim()) {
    return NextResponse.json({ error: "指示概要（overview）は必須です" }, { status: 400 });
  }

  const rank: AssigneeRank = VALID_RANKS.includes(assignee_rank as AssigneeRank)
    ? (assignee_rank as AssigneeRank)
    : "B";
  const mode: SupportMode = support_mode === "coaching" ? "coaching" : "efficiency";

  try {
    const overrides = await getTenantModelOverrides();
    const modelOverride = (draft.importance === "high" ? overrides.high : overrides.standard) ?? undefined;

    const ctx = await getCurrentUserContext();
    const effectiveTeamId = team_id || ctx?.teamId || null;
    let categoryOverrides: TeamCategoryOverride[] = [];
    if (effectiveTeamId) {
      const supabase = getSupabaseServer();
      const { data } = await supabase
        .from("team_categories")
        .select("team_id, major, major_label, sub, sub_label")
        .eq("team_id", effectiveTeamId);
      categoryOverrides = (data ?? []) as TeamCategoryOverride[];
    }
    const categories = flattenCategories(mergeTeamCategories(categoryOverrides));

    // Scores only — final_instruction/milestones are generated by a
    // follow-up call to /api/evaluate/finalize, made only when this result
    // is passed. This is what actually cut the 120s+ timeouts documented
    // above: "evaluate → revise → re-submit" is the normal flow, so most
    // calls here no longer pay for generating a final_instruction that
    // would just be thrown away. Kept as a full Evaluation shape (empty
    // final_instruction, null milestones) so existing clients/types don't
    // need to change for the fields that are unaffected by the split.
    const score = await scoreInstruction(draft, rank, mode, modelOverride, categories);
    return NextResponse.json({ ...score, final_instruction: "", milestones: null });
  } catch (err) {
    console.error("[/api/evaluate]", err);
    // Routes through the client's existing 504 handler (fetchEvaluation in
    // WorkflowClient.tsx), which already shows a friendly Japanese message
    // suggesting the "通常" precision mode as a faster retry path.
    if (err instanceof APIConnectionTimeoutError) {
      return NextResponse.json({ error: "AIの応答がタイムアウトしました。" }, { status: 504 });
    }
    // 内部例外の生メッセージをそのままユーザーに見せない。詳細は上の
    // console.errorでログに残し、画面には分かりやすい文言だけ返す。
    return NextResponse.json(
      { error: "評価中にエラーが発生しました。お手数ですが、もう一度「評価する」を押してください。" },
      { status: 500 },
    );
  }
}
